### ISSUE TITLE
infoblox-client in awx-ee not working

### ISSUE THREAD

**Issue by slasse** [ansible/awx-ee#108]
I am trying to add the infoblox-client package to our awx-ee image but i can't get it to work.
it keeps giving me: "msg": "infoblox-client is required but does not appear to be installed.  It can be installed using the command `pip install infoblox-client`"

I have cloned the awx-ee base image and added _"infoblox-client"_ to the requirement.yml file for the python package needed 
and added _"infoblox.nios_modules"_ to the collections requirements.yml file to add the ansible collection for the module.

Doing that on a regular ubuntu for examle is enough to have it working.

If i check in the container everything seems to be installed.
![image](https://user-images.githubusercontent.com/5870570/160091966-8cd3a95c-d0ad-4fe1-8a85-3e95a56f05b7.png)

One difference i noticed comparing it to a regular install is that on that system a python library is added in /usr/lib/python3/dist-packages/ansible/modules/net_tools/nios and that is nowhere to be found in the awx-ee image.
I looked in /usr/local/lib/python3.8/site-packages/ansible/module_utils/ which i assume is where ansible is looking for the files based on this screenshot.
![image](https://user-images.githubusercontent.com/5870570/160094880-b5478814-bde5-42de-b3e6-9f894df970e9.png)

Which is where found that library on the regular ubuntu:
![image](https://user-images.githubusercontent.com/5870570/160095123-6b350b46-783e-4179-b3c9-1c9dfc5e32b7.png)

I tried to add the library in the image manually but it wasn't picked up.

It seems that some files that are normally installed with the python infoblox-client package are not being installed in the image for some reason

Any advice would be much appreciated

**Comment by ffirg** [comment]
Hi @slasse this repo isn't for support type issues, so I suggest you head on over to the awx mailing support list https://groups.google.com/g/awx-project for further assistance with this.

What I would say is look at https://docs.ansible.com/ansible/latest/reference_appendices/python_3_support.html#using-python-3-on-the-managed-machines-with-commands-and-playbooks as this is often the cause especially if you are using localhost.
