### ISSUE TITLE
Don't kill me, but... can awx-ee be created based on a different OS than CentOS 8 stream?

### ISSUE THREAD

**Issue by cmasopust** [ansible/awx-ee#111]
Hi guys,
sorry for this dumb newbie question... is it possible to build awx-ee based on, e.g. Debian?  How?

Thanks,
Christian

**Comment by rebeccahhh** [comment]
Hello, your question seems like a good one to ask on our mailing list at https://groups.google.com/g/awx-project. You can also join #ansible-awx on https://libera.chat/ and ask your question there.
We welcome all newbie questions there! There are no dumb questions. :)
