### ISSUE TITLE
Projects git sync fails

### ISSUE THREAD

**Issue by guliaka** [ansible/awx-ee#116]
Started today on all projects sync fails with error: ERROR! Unexpected Exception, this is probably a bug: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'

Full trace:

Traceback (most recent call last):
  File &quot;/usr/local/bin/ansible-galaxy&quot;, line 97, in &lt;module&gt;
    mycli = getattr(__import__(&quot;ansible.cli.%s&quot; % sub, fromlist=[myclass]), myclass)
  File &quot;/usr/local/lib/python3.8/site-packages/ansible/cli/galaxy.py&quot;, line 24, in &lt;module&gt;
    from ansible.galaxy.api import GalaxyAPI
  File &quot;/usr/local/lib/python3.8/site-packages/ansible/galaxy/api.py&quot;, line 28, in &lt;module&gt;
    from ansible.module_utils.urls import open_url, prepare_multipart
  File &quot;/usr/local/lib/python3.8/site-packages/ansible/module_utils/urls.py&quot;, line 115, in &lt;module&gt;
    from urllib3.contrib.pyopenssl import PyOpenSSLContext
  File &quot;/usr/lib/python3.8/site-packages/urllib3/contrib/pyopenssl.py&quot;, line 46, in &lt;module&gt;
    import OpenSSL.SSL
  File &quot;/usr/local/lib/python3.8/site-packages/OpenSSL/__init__.py&quot;, line 8, in &lt;module&gt;
    from OpenSSL import crypto, SSL
  File &quot;/usr/local/lib/python3.8/site-packages/OpenSSL/crypto.py&quot;, line 1517, in &lt;module&gt;
    class X509StoreFlags(object):
  File &quot;/usr/local/lib/python3.8/site-packages/OpenSSL/crypto.py&quot;, line 1537, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
AttributeError: module &apos;lib&apos; has no attribute &apos;X509_V_FLAG_CB_ISSUER_CHECK&apos;

**Comment by guliaka** [comment]
I guess it fails in same spot as #115  and #112

**Comment by fegmorte** [comment]
@guliaka If you use awx-operator, you can change the awx-ee version under AWX Administration menu --> Execution environment and replace quay.io/ansible/awx-ee:latest by quay.io/ansible/awx-ee:0.6.0. That works for me as a workaround.

**Comment by guliaka** [comment]
@fegmorte  Did not work for me:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ansible_runner/__main__.py", line 861, in main
    res = run(**run_options)
  File "/usr/local/lib/python3.8/site-packages/ansible_runner/interface.py", line 257, in run
    r.run()
  File "/usr/local/lib/python3.8/site-packages/ansible_runner/streaming.py", line 128, in run
    r = ansible_runner.interface.run(**self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/ansible_runner/interface.py", line 256, in run
    r = init_runner(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/ansible_runner/interface.py", line 118, in init_runner
    rc = RunnerConfig(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/ansible_runner/config/runner.py", line 78, in __init__
    super(RunnerConfig, self).__init__(private_data_dir, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'suppress_env_files'


  This can be caused if the version of ansible-runner in your execution environment is out of date.

**Comment by fegmorte** [comment]
@guliaka finally the latest version works again for me. Do you try it again ?
A build happens every 12h.

**Comment by eselvam** [comment]
Yes. we also got same error: awx AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK



as we used custom Ee to over come this. shall we know when we can expect AWX EE to be patched to fix this?

**Comment by fegmorte** [comment]
@eselvam it seems the issue comes from cryptography 37.0.0 Not Compatible with pyOpenSSL
- [https://github.com/pyca/pyopenssl/pull/1117](https://github.com/pyca/pyopenssl/pull/1117)
- [https://github.com/pyca/cryptography/issues/7126](https://github.com/pyca/cryptography/issues/7126)

I retried with the latest build and it works again for me

**Comment by guliaka** [comment]
Latest build seems work. Pulling it to my local registry and pinning it in my config for now.
