### ISSUE TITLE
Blowfish error in latest AWX-EE

### ISSUE THREAD

**Issue by john-westcott-iv** [ansible/awx-ee#118]
When running a job in the latest awx-ee container a warning about blowfish is presented in the job output:
```
/usr/local/lib/python3.8/site-packages/paramiko/transport.py:236: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
/usr/local/lib/python3.8/site-packages/paramiko/transport.py:236: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
```

Paramiko is working on a fix: https://github.com/paramiko/paramiko/issues/2038

**Comment by rebeccahhh** [comment]
If anyone is wondering how we're going to fix this, the fix that @john-westcott-iv mentioned will automatically get pulled in, aka this will resolve itself soon. :)
Closing since it's not an action item, good find John.
