### ISSUE TITLE
How can i fix Vulnerabilities in AWX-EE 0.6.0

### ISSUE THREAD

**Issue by tapankb2019** [ansible/awx-ee#121]
Hi Team,

Could you please help us to fix Vulnerabilities in AWX-EE 0.6.0,I could see below vulnerabilities reported

Quay Security Scanner has detected 31 vulnerabilities.
 2 Critical-level vulnerabilities.
 10 High-level vulnerabilities.
 15 Medium-level vulnerabilities.
 4 Unknown-level vulnerabilities.

Thanks

**Comment by shanemcd** [comment]
Hello. We no longer build AWX EE 0.6.0. Right now we're only actively building and pushing latest. I realize that's not awesome, but we dont have the resources to do better right now.
