### ISSUE TITLE
ee basic requirements is not satisfied

### ISSUE THREAD

**Issue by amg-web** [ansible/awx-ee#122]
I found that some basic requirements is not met.

**dnspython** required by  **dig** lookup plugin is not available, and playbook fails.
also some preinstalled collections does not have all required python modules.

eg.
**azure.azcollection** included in
https://github.com/ansible/awx-ee/blob/devel/_build/requirements.yml
does not have **azure-cli** dependency satisfied.

**Comment by relrod** [comment]
> dnspython required by dig lookup plugin is not available, and playbook fails.

We don't include `community.general` which is where the dig lookup plugin lives. If you need this plugin (and its deps), you likely want to make a custom EE. You can find documentation on that process here: https://docs.ansible.com/automation-controller/latest/html/userguide/execution_environments.html

> azure.azcollection included in
> https://github.com/ansible/awx-ee/blob/devel/_build/requirements.yml
> does not have azure-cli dependency satisfied.

I don't believe azure-cli is a dependency - at least I can't find any `azure.azcollection` docs that imply that. In any case, if there's a dependency missing there, you likely want to report it to the [upstream collection](https://github.com/ansible-collections/azure/) (or if you just want the CLI available, then create a custom EE as described in the link above).

I don't think there is anything actionable here, so I'm going to close this out. If I've missed something, let me know!

**Comment by amg-web** [comment]
very strange.
it's basics for dns. and is not included? 
I think we should consider community.general requirements to be included by default
