### ISSUE TITLE
tag awx-ee images with corresponding awx image tags

### ISSUE THREAD

**Issue by fosterseth** [ansible/awx-ee#125]
Right now we just have `latest` but seems the community would appreciate having distinct tags for awx-ee to rely on. see https://github.com/ansible/awx-operator/issues/965

@shanemcd had the idea of just tagging images with whatever the current awx image tag is each time we build awx-ee

**Comment by gundalow** [comment]
Seems like a useful thing

Need to work out where this should be documented (so folks know they can take advantage of it)

I think this would be a great item for The Bullhorn, I can walk you through that process.

**Comment by john-westcott-iv** [comment]
Possibly related: https://github.com/ansible/awx-ee/issues/117

**Comment by sjpb** [comment]
This is critical - currently we can't even pin using the sha256 hash as apparently that changes if `latest` gets updated. E.g. yesterday `latest` could be referenced as `quay.io/ansible/awx-ee@sha256:1b9564e397a5059b53d304a697fcc48250fb805caf828a8006ef799d69a8dd21`, today it can't be as the hash is now `8c40540b25a8...`.

Surely:
- `latest` should also be tagged with a version number e.g. `0.6.1` or whatever
- released images should not be removed?

**Comment by Cl0udius** [comment]
We would also highly appreciate this. 
As there were some problems in the last weeks with latest state a version tag for the 21.x compatible versions would be very useful.

**Comment by r0b1ndot** [comment]
We would also highly appreciate this.
Since we want to better control the lifecycle of our deployments, so this would be very useful.

**Comment by texasbobs** [comment]
Just wanted to add to this... we have a requirement to not use `latest` so if other tags could be created, that would help.

**Comment by codepoke-kk** [comment]
Add me to the list on this one. I'm not allergic to the word "latest", but I am allergic to a situation where the stack breaks against a numbered version. Whenever a working stack is broken such that a new EE is needed, someone should drive a stake in the ground with a tagged version so we can be sure it won't change under us. I cannot verify, but I have to assume there was a moment in time when the "latest" EE just suddenly stopped working on a simple restart, and that's a show-stopper.

**Comment by relrod** [comment]
This has been implemented as of this past AWX release. Closing this now.

**Comment by gannaramu** [comment]
@relrod  container images are tagged but the corresponding tags are not present on this git repo.

**Comment by AndrewSav** [comment]
Yeah, was also surprised by this. Should we open a new issue to track that, or just re-open that one? Obviously the image tag needs to correspond to source control tag so we know which version of the source the image is built from.

**Comment by gannaramu** [comment]
@relrod any update on this request?
