### ISSUE TITLE
Github Action step for build image seem to hang

### ISSUE THREAD

**Issue by thedatabaseme** [ansible/awx-ee#138]
Hello,

I'm not sure if you're aware of this, but your workflow for build and push EE images is not working since a few days. I observed this also in some repos of mine. The actual ansible-builder build process seem to take ages and will be canceled due to long runtime.
Do you have any clue why this behavior started 2-3 days ago?

Kind regards
Philip

**Comment by kurokobo** [comment]
Wow I had just created the exact same issue a few minutes ago; #137

**Comment by kurokobo** [comment]
@thedatabaseme 
F.Y.I. I've made quick investigation and posted super dirty workaround; https://github.com/ansible/awx-ee/issues/137#issuecomment-1264596725
Maybe this hack can be used for your repos.

And if it's okay for you, this can be closed as duplicate of #137

**Comment by thedatabaseme** [comment]
Closed as duplicate of #137
