### ISSUE TITLE
Unable to manage collection using _build/requirements.*

### ISSUE THREAD

**Issue by cdivriotis97** [ansible/awx-ee#146]
Hi,

I am writing to you, because I do not know what to do.
I used this repo to build my EE in AWX.

I wanted to add the collection community.general, so I added to requirement.yml:
![image](https://user-images.githubusercontent.com/116892320/199497638-0d81084a-4845-4109-9de5-f83c346519b0.png)

I re-build a new image using tox, but when the new container is up, I got this on AWX:
![image](https://user-images.githubusercontent.com/116892320/199498015-6fe92d4b-c3e8-4d96-ab22-d6d7368eb24d.png)

So, I added this line in the requirements.txt:
![image](https://user-images.githubusercontent.com/116892320/199498104-5e4c32e1-f23f-4c89-8c17-7f228c90c233.png)

But, it seems that none of the requirements present on requirements.txt are applied.

To bypass that, I also tried to use my actual EE and to install what I wanted on the container directly and then commit on a new image.
It isn't working.
When I use ansible-galaxy to install community.general, AWX doesn't seem to find the module (but the module is present on the container !!):
![image](https://user-images.githubusercontent.com/116892320/199498700-681bf98f-0bc6-46dd-a477-6b19a8337b28.png)

Can you guide me ? I tried a lot of things, but none of them are working.
What I want is to be able to add / remove / manage the collection ..

Thank you in advance for your kind help !

**Comment by AlexSCorey** [comment]
@snoopyx21 Hello, this appears to be less of a bug report or feature request and more of a question. Could you please ask this on our mailing list? See https://github.com/ansible/awx/#get-involved for information for ways to connect with us.

**Comment by cdivriotis97** [comment]
Hi @AlexSCorey 

My bad, really, I was looking for this.
Thank you, I will close the ticket. You can remove it also if you want.
