### ISSUE TITLE
Upon digest changes, images cannot be download

### ISSUE THREAD

**Issue by blueprismo** [ansible/awx-ee#151]
Hello, Today I tried to pull this "fixed" image: 
`quay.io/ansible/awx-ee@sha256:35506bfa954caa562b31adfe8d94efb64666c1d16d27531f02b248d311acc227`
And as today's "latest" tag has been updated, the image's digest also changed, so I got an error calling `manifest-unknown`.
So I tried to look it up also in the ["previous" latest tag](https://quay.io/repository/ansible/awx-ee/manifest/sha256:35506bfa954caa562b31adfe8d94efb64666c1d16d27531f02b248d311acc227), and the image isn't there anymore.
Is there a reason you delete the intermediate docker images, or could you add some fixed tags recently? (latest fixed tag is 0.6.0 which is pretty old)

**Comment by relrod** [comment]
I'm going to close this out as a duplicate of #125. We are looking to start tagging awx-ee as part of the awx release process going forward!
