### ISSUE TITLE
Update Git dependency

### ISSUE THREAD

**Issue by ng-bsy** [ansible/awx-ee#154]
AWX-EE is stuck with Git version 2.31.
Putting `git >=2.37.0` in the bindep.txt and rebuilding the image doesn't work - resulting image is still stuck at 2.31.

How to proceed?

Thanks

**Comment by akus062381** [comment]
Hi @ng-bsy, thank you for your submission.

The awx-ee contains the collections and dependencies needed for supported AWX features to function. Anything beyond that (like the community.general package) will require you to build your own EE. For information on how to do that, see https://ansible-builder.readthedocs.io/en/stable/

**Comment by ng-bsy** [comment]
> Hi @ng-bsy, thank you for your submission.
> 
> The awx-ee contains the collections and dependencies needed for supported AWX features to function. Anything beyond that (like the community.general package) will require you to build your own EE. For information on how to do that, see https://ansible-builder.readthedocs.io/en/stable/

Hi @akus062381,

thank you for your reply.

As you can see from my initial description I am already trying to do _exactly what you suggested_.

However for some reason the system dependencies, as explained in https://ansible-builder.readthedocs.io/en/stable/definition/#dependencies are not recognized/adhered to, when I, like already described, put `git >=2.37.0` in the bindep.txt and build the image.

So I was wondering, if _maybe_ you guys are doing some stuff in the background like pinning to a fixed version, that would overwrite any change I'm doing to that specific dependency and would like to know how to circumvent this.

This issue is **not solved** - closing it like this with a response that shows, the issue has either not been read or not understood is kind of ....

Could someone with more technical experience in this area respond to this, please?

Should I open a new ticket as I seem not to be able to reopen it?
