### ISSUE TITLE
community.vmware warning, too old ansible-core in quay.io/ansible/awx-ee

### ISSUE THREAD

**Issue by raskallen** [ansible/awx-ee#156]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

When running playbooks using community.vmware, I am getting this warning: 

![image](https://user-images.githubusercontent.com/20677664/211748246-141c5095-f274-4dcc-9c43-e13bf3a7b3ae.png)

I was at 20.0.0, so I figured I needed an upgrade, but after upgrading to 21.10.2, the waring is still there.

I then checked the packages in quay.io/ansible/awx-ee and found out that ansible-core is at version 2.12.5. I think this should be updated.

My playbooks work, but I think ansible-core should be supported by the collections included in the image.

### AWX Operator version

1.1.3

### AWX version

21.10.2

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6+k3s1", GitCommit:"3228d9cb9a4727d48f60de4f1ab472f7c50df904", GitTreeState:"clean", BuildDate:"2022-01-25T01:27:44Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}

### Modifications

yes

### Steps to reproduce

Run a playbook using the community.vmware collection. 

### Expected results

The successful execution of the template without errors or warnings.

### Actual results

Successful execution of the template with the following warning:

[WARNING]: Collection community.vmware does not support Ansible version
2.12.5.post0

### Additional information

I set "max_locks_per_transaction = 1000" in postgresql.conf. Shouldn't be relevant for this issue.

### Operator Logs

Using /runner/project/ansible.cfg as config file
[WARNING]: Collection community.vmware does not support Ansible version
2.12.5.post0

**Comment by fosterseth** [comment]
@shanemcd seems awx-ee installs collections that aren't compatible the ansible version that is installed

```
docker run  quay.io/ansible/awx-ee:latest ansible --version
ansible [core 2.12.5.post0]
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.13 (default, Jun 24 2022, 15:27:57) [GCC 8.5.0 20210514 (Red Hat 8.5.0-13)]
  jinja version = 2.11.3
  libyaml = True
```

should we bump the ansible core version to 2.13 or later?

**Comment by shanemcd** [comment]
So this is a bit of a rabbit hole. Newer versions of Ansible require a version of Python that is not available in EL 8. I started looking at moving to EL 9 for other reasons but unfortunately all of the base images used by the current version of ansible-builder are EL 8.

I ended up hacking this together as an experiment: https://github.com/ansible/awx-ee/compare/devel...manual-ish

This _almost_ worked but I ran into a problem with the ovirt collection. I opened up a PR here that just got approved: https://github.com/oVirt/ovirt-ansible-collection/pull/657. Once that merges I think we should apply this hack to awx-ee until the next major version of ansible-builder ships.

**Comment by austlane** [comment]
Until newer versions of Ansible can be used. https://github.com/ansible/awx-ee/pull/144 addresses this compatibility issue.

**Comment by shanemcd** [comment]
https://github.com/ansible/awx-ee/pull/160

**Comment by relrod** [comment]
#160 merged and new ansible and centos stream are used on the `latest` tag now.

Any objections to closing this out?
