### ISSUE TITLE
pywinrm is no longer in the latest awx:ee image

### ISSUE THREAD

**Issue by it-pappa** [ansible/awx-ee#163]
Missing pywinrm package in the latest awx:ee image.

**Comment by pmanno** [comment]
Same situation here.
"msg": "winrm or requests is not installed: No module named 'winrm'",

**Comment by it-pappa** [comment]
@pmanno yes, it is multiple packages missing. 
Guess they will fix it very soon

**Comment by it-pappa** [comment]
pykerberos still missing.
Issue: https://github.com/ansible/awx-ee/issues/166
