### ISSUE TITLE
Added new EE kills AWX

### ISSUE THREAD

**Issue by it-pappa** [ansible/awx-ee#172]
Just added EE 21.11.0 to test a playbook since i get errors in the latest one (still). 
(I added and did not change the awx EE). 

When running win_ping agains a inventory host, AWX gave bad gateway and killed the whole thing. AWX doesnt work anymore?

**Comment by it-pappa** [comment]
Update:
After a hard restart og the server and wait for a while. It is up and running again.
Looks like a timeout when downloading an EE?

**Comment by shanemcd** [comment]
I just responded to you over on https://github.com/ansible/awx/issues/13534 - in the future please dont spam multiple issue trackers with the same thing - especially without linking them.
