### ISSUE TITLE
Openstack dynamic inventory broken

### ISSUE THREAD

**Issue by per-lind** [ansible/awx-ee#197]
Using the openstack inventory plugin is currently broken when using private IPs. The fix have been added here https://storyboard.openstack.org/#!/story/2010614 but no new release yet. 
Would it be an idea to downgrade the openstack.cloud to 1.x while we give 2.x some time to get more stable?

**Comment by fosterseth** [comment]
@shanemcd just pinging so that this is on your radar, not sure we need to pin or have users just build their own EE with the needed version

**Comment by shanemcd** [comment]
I'd just leave it broken until the fix lands. If folks want the fix sooner they can build their own images. We can leave this open for now in case other people run into this, and close once the patch makes its way into our builds.

**Comment by per-lind** [comment]
This is now fixed upstream
