### ISSUE TITLE
AWX-ee repos issue

### ISSUE THREAD

**Issue by pradeep-git23** [ansible/awx-ee#211]
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
ERROR! Unexpected Exception, this is probably a bug: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
The command '/bin/sh -c ansible-galaxy role install $ANSIBLE_GALAXY_CLI_ROLE_OPTS -r requirements.yml --roles-path "/usr/share/ansible/roles"' returned a non-zero code: 250

**Comment by fosterseth** [comment]
are you using awx-ee:latest or building your own?

can you look at your requirements/requirements.txt and make sure cryptography library is up to date

**Comment by pradeep-git23** [comment]
we are building it own
My Requiremnet.txt file contain this
pywinrm
boto3
pypsrp
pysocks

**Comment by pradeep-git23** [comment]
@fosterseth how to make sure of "make sure cryptography library is up to date" this ? If you can guide me that will be really helpfull

**Comment by fosterseth** [comment]
closing this ticket, please reach out to us on the mailing list https://github.com/ansible/awx/#get-involved
