### ISSUE TITLE
How to make sure the compatibility between the AWX component.

### ISSUE THREAD

**Issue by pradeep-git23** [ansible/awx-ee#213]
Hi Team, Can anyone let me know or share the details or list which contain the compatibility of awx- runner,builder, awx,ee & operator

**Comment by fosterseth** [comment]
Hello, this appears to be less of a bug report or feature request and more of a question. Could you please ask this on our mailing list? See https://github.com/ansible/awx/#get-involved for information for ways to connect with us.
