### ISSUE TITLE
Assistance for customizing Containerfiles

### ISSUE THREAD

**Issue by SebastianLeitz** [ansible/awx-ee#214]
My company has an existing infrastructure to customize container images (e.g. inject package mirrors, company certs or proxy information). The infrastructure is based on container files (e.g. `Dockerfile`) and Docker Buildkit.  
In the past, we also used this infrastructure to customize the AWX EE images we were using internally. Every few months I would take another look at the image file in this repository and cherry-pick some of the upstream changes into ours.

Some time ago, this repository switched to using `ansible-builder`, which uses a different approach to get to the same result. Probably works fine, but there is no plain container file available anymore to reference.

How do people work with this for customizations? I see that we could create a separate build chain for our internal AWX EE images that does not use Docker BuildKit but ansible-builder. Or one could reverse engineer how a container definition would need to look like that has the same result as the configuration in this repository.

Does anybody have some insight on how they are doing it?

**Comment by seadoox** [comment]
I use ansible-builder create -v3 to dump the full context of what is used to build the container including the Containerfile. I'm doing that with gitlab-ci to automate building new images regularly but you could do it manually just to dump the containerfile and compare it to the last one you had.

**Comment by SebastianLeitz** [comment]
That is exactly what I was looking for without knowing the tools. Thank you very much @seadoox!
