### ISSUE TITLE
Finish upstream changes so we can make an Ansible 2.9 version

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx-ee#28]
Migrating from https://github.com/ansible/ansible-builder/issues/67, at this very moment we still have 2 outstanding things:

 - https://storyboard.openstack.org/#!/story/2007990 https://review.opendev.org/c/openstack/ansible-collections-openstack/+/750972
 - https://github.com/oVirt/ovirt-ansible-collection/pull/197

In addition to this, we need to remove the git requirement for `community.kubernetes`, because it's at parity with the released version.

**Comment by AlanCoding** [comment]
related https://github.com/ansible/awx-ee/pull/29

**Comment by shanemcd** [comment]
I don't think we're going to have an Ansible 2.9 awx-ee
