### ISSUE TITLE
Default EE should be using a release version of ansible

### ISSUE THREAD

**Issue by lemmy04** [ansible/awx-ee#55]
Right now the default EE that is deployed alongside AWX is built around ansible-core 2.11 which is not released yet.
also, the image contains only 900-some modules compared to what is shipped with a released ansible 2.9.x which contains over 3000 modules.

Also, the ansible version inside the awx-ee image isn't even installed from a rpm...

Please provide an EE image based around ansible 2.9.x with all official modules present, and where ansible was installed from an official rpm for the base OS of the image.

**Comment by shanemcd** [comment]
Welcome to life on the bleeding edge of a fast-moving project. Things will settle down eventually.
