### ISSUE TITLE
Request to include the pexpect library

### ISSUE THREAD

**Issue by AlanCoding** [ansible/awx-ee#56]
Follow up from issue https://github.com/ansible/awx/pull/4995

I take it this is needed for `ansible.builtin.expect` @tha80 @kladiv is that your use case?

https://docs.ansible.com/ansible/latest/collections/ansible/builtin/expect_module.html

**Comment by kladiv** [comment]
@AlanCoding yes, it could be useful in EE image too

**Comment by kladiv** [comment]
In AWX EE "quay.io/ansible/awx-ee:0.3.0" module `pexpect==4.8.0` seems installed by default.
