### ISSUE TITLE
Collection not included in default EE

### ISSUE THREAD

**Issue by njordhr** [ansible/awx-ee#65]
The same case like in [https://github.com/ansible/awx/issues/9863](url)

There is no collection compatibility between AWX =<17 and AWX >=18. This is still missing: 

- community.general

Pull requests [#64 ](url)

**Comment by shanemcd** [comment]
I think we are unlikely to do this. We're trying to keep upstream and downstream aligned and we will not be supporting the content in `community.general` on our end. If you need to use it, you'll have to build your own EE.
