### ISSUE TITLE
Error: ImagePullBackOff

### ISSUE THREAD

**Issue by sudharsanomprakash** [ansible/awx-ee#73]
I have AWX Tower 18.0.0 running on AKS Cluster. While launching the job templates, awx-job-61-p25bk pod is trying to get created but it is failing with Error: ImagePullBackOff.

kubectl logs pods/awx-job-61-p25bk -n awx
Error from server (BadRequest): container "worker" in pod "awx-job-61-p25bk" is waiting to start: trying and failing to pull image

Events:
  Type     Reason          Age                From               Message
  ----     ------          ----               ----               -------
  Normal   Scheduled       77s                default-scheduler  Successfully assigned awx/awx-job-61-p25bk to aksd2msw000003
  Normal   Pulling         63s (x2 over 75s)  kubelet            Pulling image "quay.io/ansible/awx-ee"
  Warning  Failed          63s (x2 over 74s)  kubelet            Failed to pull image "quay.io/ansible/awx-ee": rpc error: code = Unknown desc = Error response from daemon: unknown: Tag latest was deleted or has expired. To pull, revive via time machine
  Normal   SandboxChanged  51s (x7 over 74s)  kubelet            Pod sandbox changed, it will be killed and re-created.
  Warning  Failed          47s (x6 over 71s)  kubelet            Back-off pulling image "quay.io/ansible/awx-ee"

**Comment by wenottingham** [comment]
This issue tracker is for tracking feature enhancements and bugs to the AWX execution environment image itself.

If you need help troubleshooting an AWX install, try our mailing list or IRC channel:

Mailing list: https://groups.google.com/forum/#!forum/awx-project
IRC: ansible-awx on irc.libera.chat
