### ISSUE TITLE
Publish latest tag to the container registry

### ISSUE THREAD

**Issue by mo-saeed** [ansible/awx-ee#74]
Could you please include tag "latest" to https://quay.io/repository/ansible/awx-ee this can help us building custom image using the latest release

**Comment by wenottingham** [comment]
This is controlled by a build pipeline in the repo under `.github` - feel free to send a PR for this.

**Comment by relrod** [comment]
We have a `latest` tag now (updated daily) and we're working to have tags that correspond to AWX releases soon! Going to close this out.
