### ISSUE TITLE
Elevated privileges / root password

### ISSUE THREAD

**Issue by azrdev** [ansible/awx-ee#89]
Using the 0.5 version of this container as EE in AWX19, I'd like to do some container-wide configuration. This is not possible, because the user is not root and `su` requires a password unknown to me.

## example

~~~yaml
- name: configure pip mirror
  ini_file:
    path: /etc/pip.conf
    section: global
    option: index
    value: https://internal.pip.mirror.example.com
  delegate_to: localhost

- name: install API pkg locally
  pip:
     name: api-client
  delegate_to: localhost
~~~

Yes, a long-term solution would be to include the package in an own build of the EE container, but especially for development iterations this would be useful.

**Comment by shanemcd** [comment]
Sorry we're not going to make changes to this EE to make development easier. At that point, you need to build your own.
