### ISSUE TITLE
Add google-cloud-storage module by default in AWX EE

### ISSUE THREAD

**Issue by kladiv** [ansible/awx-ee#91]
Hello,
is it possible to add `google-cloud-storage` pip module in AWX EE ?

google-auth module is already present but to use *google.cloud.gcp_storage_bucket* Ansible module the google-cloud-storage library is required too.
It should be useful to have it built-in in the default EE.

Thank you

**Comment by shanemcd** [comment]
Sure. Can you open a PR?

**Comment by relrod** [comment]
This gets pulled in automatically via the `google.cloud` collection's requirements.txt file.

```
bash-4.4$ pip list  2>/dev/null | grep google-cloud-storage
google-cloud-storage               2.7.0
```
